using System;

public class GameSearch
{
    public int GameID { get; set; }
    public int GameNumber { get; set; }
    public DateTime StartDate { get; set; }
    public int LotteryID { get; set; }
    public string GameReferenceID { get; set; }
    public string GameName { get; set; }
    public string GameNameInEnglish { get; set; }
    public string CurrencyCode { get; set; }
    public string CurrencySymbol { get; set; }
    public double TicketPrice { get; set; }
    public int TicketsReceived { get; set; }
    public int TicketsOrdered { get; set; }
    public string TicketsPerBook { get; set; }
    public double Odds { get; set; }
    public double PrizePayoutPercent { get; set; }
    public string PaperStock { get; set; }
    public string Orientation { get; set; }
    public int Height { get; set; }
    public int Width { get; set; }
    public int NumPlayAreas { get; set; }
    public int NumPlayStyle { get; set; }
    public bool LicensedProperty { get; set; }
    public bool MultipleScenes { get; set; }
    public int NumChancesToWin { get; set; }
    public int NumCallouts { get; set; }
    public bool SecondChance { get; set; }
    public bool CoreGame { get; set; }
    public bool GameFamily { get; set; }
    public bool MultiColorImaging { get; set; }
    public bool LowMarquee { get; set; }
    public bool Spotlight { get; set; }
    public bool ProprietaryID { get; set; }
    public bool LowTopPrize { get; set; }
    public bool LimitedTier { get; set; }
    public double CalcOdds { get; set; }
    public double CalcPrizePayoutPercent { get; set; }
    public bool NoBreakeven { get; set; }
    public string BusinessName { get; set; }
    public string CurrencyType { get; set; }
    public string ProprietaryName { get; set; }
    public string Theme { get; set; }
    public string Feature { get; set; }
    public string PlayStyle { get; set; }
    public string Color { get; set; }
    public string SpecialtyOption { get; set; }
    public int PrimaryThemeID { get; set; }
    public string SecondaryThemeID { get; set; }
    public int PrimaryFeatureID { get; set; }
    public string SecondaryFeatureID { get; set; }
    public int PrimaryPlayStyleID { get; set; }
    public string SecondaryPlayStyleID { get; set; }
    public int PrimaryColorID { get; set; }
    public int SecondaryColorID { get; set; }
    public string PrimarySpecialtyOptionID { get; set; }
    public string SecondarySpecialtyOptionID { get; set; }
    public string ImgName { get; set; }
    public string SubDivisionCode { get; set; }
    public string SubDivisionName { get; set; }
    public bool IsTopPrize { get; set; }
    public int PrizeAmount { get; set; }
    public int NumberOfPrizes { get; set; }
    public string PrizeTypeName { get; set; }
    public double CurrentYearSales { get; set; }
    public double LastYearSales { get; set; }
    public double Last2YearSales { get; set; }
    public string Index { get; set; }
    public bool IsFeatured { get; set; }
    public int IsWorkingPapers { get; set; }
}